// flow-typed signature: bec7b9cfc1c164e36414a587daad5ffa
// flow-typed version: <<STUB>>/koa-compose_vx.x.x/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-compose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-compose' {
  declare module.exports: any;
}
