// flow-typed signature: 308a9e44e9007b2a98065ce294efc275
// flow-typed version: <<STUB>>/winston-daily-rotate-file_vx.x.x/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston-daily-rotate-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston-daily-rotate-file' {
  declare module.exports: any;
}
