// flow-typed signature: acd1f5f9c1b1e2a557d0b074c533c835
// flow-typed version: <<STUB>>/winston_vx.x.x/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston' {
  declare module.exports: any;
}
